name : CI CD

on :
  push :
    branches : [ dev ]

jobs :
  build :
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11.0.2
        uses: actions/setup-java@master
        with:
          java-version: 11.0.2
      - name: Build Fat Jar
        run: sbt assembly
      - name: S3 Upload Jar
        uses: jakejarvis/s3-sync-action@dev
        with:
          args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}/jar/
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-south-1'
        FILE: 'target/scala-2.12/spark2livedemo_2.12-*.jar'